on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Change directory to server-test-backend
        run: cd ./server-test-backend

      - name: Install flashpick backend Server Dependencies
        run: npm install

      - name: Run tests
        run: npm run test
