on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install flashpick backend Server Dependencies
        run: cd ./server-test-backend npm install

      - name: Run tests
        run: cd ./server-test-backend npm run test
