on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install flashpick backend Server Dependencies
        run: npm install

      - name: Run tests # Run tests of all packages
        run: npm run test
