on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Change directory to server-test-backend
        working-directory: ./server-test-backend
        run: cd .

      - name: Install flashpick backend Server Dependencies
        run: npm install

      - name: Run tests
        run: npm run test
